### ISSUE TITLE
lineLimit off by 1

### ISSUE THREAD

**Issue by hgardneriv** [srobinson2018/log-collection#7] opened 2022-08-11 20:54 UTC
When using the lineLimit parameter the number of lines returned is off by 1. 

Examples:

** lineLImit 1:**

```
$ curl  "http://localhost/logs?fileName=jamf.log&lineLimit=1"
$ 
```

**lineLimit 2**
```
$ curl  "http://localhost/logs?fileName=jamf.log&lineLimit=2"

Thu Aug 11 15:36:25 My MacBook Pro jamf[12759]: Removing existing launchd task /Library/LaunchDaemons/com.jamfsoftware.task.bgrecon.plist..%               $ 
$
```

**lineLimit 4**

```
$ curl  "http://localhost/logs?fileName=jamf.log&lineLimit=4"

Thu Aug 11 15:36:25 My MacBook Pro jamf[12759]: Removing existing launchd task /Library/LaunchDaemons/com.jamfsoftware.task.bgrecon.plist..
Thu Aug 11 15:36:08 My MacBook Pro jamf[12759]: No patch policies were found
Thu Aug 11 15:36:08 My MacBook Pro jamf[12759]: Checking for patches..%    $ 
$
```

Also note in examples of lineLimit 2 and 4 the first line is always blank. The file queried does not have a blank line at the end:

```
$ tail -4 /var/log/jamf.log
Thu Aug 11 15:36:07 My MacBook Pro jamf[12759]: Successfully installed Cribl Branding.
Thu Aug 11 15:36:08 My MacBook Pro jamf[12759]: Checking for patches...
Thu Aug 11 15:36:08 My MacBook Pro jamf[12759]: No patch policies were found.
Thu Aug 11 15:36:25 My MacBook Pro jamf[12759]: Removing existing launchd task /Library/LaunchDaemons/com.jamfsoftware.task.bgrecon.plist...
$ 
```

**Comment by srobinson2018** [comment] 2022-08-12 16:46
Thanks @hgardneriv - this bug was caused by the logic capturing that last character of the log being `\n` and handling that as its own line. I added a quick check specific to the final char in the log so this should be fixed. There is likely a more elegant solution that I will keep an eye out for as I work on some of the other improvements.

**Closed by srobinson2018** 2022-08-12 16:46 UTC
